### ISSUE TITLE
Fix dependency link

### ISSUE THREAD

**Issue by abdullah353** [forkgeeks/cloudwatch-logs-parser#19]
https://github.com/forkgeeks/cloudwatch-logs-parser/blame/master/README.md#L2 Here fix the badge link it's pointing to travis-cli

Change it to 

`[![Dependencies Status](https://david-dm.org/forkgeeks/cloudwatch-logs-parser.svg)](https://david-dm.org/forkgeeks/cloudwatch-logs-parser)`

**Comment by m-adil** [comment]
@mabdullah353  can you be more precise please as the link mentioned by you is exactly the same badge's link. Are you sure you're pointing to second i.e. Dependencies badge?

**Comment by abdullah353** [comment]
Updated My comment above, thanks for  pointing out @m-adil
